import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1776609660672 implements MigrationInterface {
    name = 'Init1776609660672'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user-token_type_enum" AS ENUM('VERIFY_EMAIL', 'RESET_PASSWORD', 'RESTORE_ACCOUNT')`);
        await queryRunner.query(`CREATE TABLE "user-token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "type" "public"."user-token_type_enum" NOT NULL, "userId" uuid, CONSTRAINT "UQ_8f5675e6be7fb584a04b6e26ca8" UNIQUE ("token"), CONSTRAINT "PK_ce0bc8c9c3bac40b0301e8e1165" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "specialization" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid, CONSTRAINT "PK_904dfcbdb57f56f5b57b9c09cc5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "About" character varying, "userId" uuid, CONSTRAINT "REL_c41a1d36702f2cd0403ce58d33" UNIQUE ("userId"), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."recommendation-batch_status_enum" AS ENUM('pending', 'active', 'completed', 'failed', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "recommendation-batch" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."recommendation-batch_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "cvId" uuid, CONSTRAINT "PK_ce68236863e6a4a5f4a08a062f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recommend-jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "final_score" double precision NOT NULL, "similarity_score" double precision NOT NULL, "skill_match_score" double precision NOT NULL, "experience_match_score" double precision NOT NULL, "seniority_match" integer NOT NULL, "matched_skills" text, "missing_skills" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "batchId" uuid, "jobId" uuid, CONSTRAINT "PK_e7895f56e9d232b3de27ccc7c9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_type_enum" AS ENUM('Full_Time', 'Part_Time', 'Contract', 'Freelance', 'Internship', 'Temporary')`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_status_enum" AS ENUM('Draft', 'Published', 'ApplicationsFull', 'Closed', 'Paused', 'Expired', 'Filled')`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_workmode_enum" AS ENUM('Onsite', 'Remote', 'Hybrid')`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_seniority_enum" AS ENUM('Fresh', 'Junior', 'Mid-Level', 'Senior', 'Lead')`);
        await queryRunner.query(`CREATE TYPE "public"."jobs_statusai_enum" AS ENUM('pending', 'active', 'completed', 'failed', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "location" character varying NOT NULL, "minSalary" numeric(10,2), "maxSalary" numeric(10,2), "type" "public"."jobs_type_enum" NOT NULL, "status" "public"."jobs_status_enum" NOT NULL DEFAULT 'Draft', "workMode" "public"."jobs_workmode_enum" NOT NULL, "seniority" "public"."jobs_seniority_enum" NOT NULL, "jobIdAi" character varying, "statusAi" "public"."jobs_statusai_enum" NOT NULL DEFAULT 'pending', "description" text NOT NULL, "positions" integer NOT NULL, "maxApplications" integer, "applicationsCount" integer NOT NULL DEFAULT '0', "acceptedCount" integer NOT NULL DEFAULT '0', "deadline" TIMESTAMP WITH TIME ZONE NOT NULL, "skills" text, "responsibilities" text, "requirements" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "companyId" uuid, CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hiredDetails" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "startDate" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "applicationId" uuid, CONSTRAINT "REL_6810b7bcf49a32fad3dacab772" UNIQUE ("applicationId"), CONSTRAINT "PK_58e69d2d78ddda9f7c54e09e669" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."jobOffer_status_enum" AS ENUM('Pending', 'Accepted', 'Rejected', 'Expired')`);
        await queryRunner.query(`CREATE TABLE "jobOffer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "offeredSalary" character varying NOT NULL, "startDate" TIMESTAMP WITH TIME ZONE NOT NULL, "notes" character varying, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "respondedAt" TIMESTAMP WITH TIME ZONE, "status" "public"."jobOffer_status_enum" NOT NULL DEFAULT 'Pending', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "applicationId" uuid, CONSTRAINT "REL_3ef8642da65cce502da7550121" UNIQUE ("applicationId"), CONSTRAINT "PK_24d6aeb541b4ceffed3ca8e2b0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."feedback_nextstep_enum" AS ENUM('Offered', 'rejected', 'Another Interview')`);
        await queryRunner.query(`CREATE TABLE "feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "publicFeedback" character varying NOT NULL, "rating" integer NOT NULL, "nextStep" "public"."feedback_nextstep_enum" NOT NULL, "resultId" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "interviewId" uuid, CONSTRAINT "REL_1da270251d13dd20cf2a50271f" UNIQUE ("interviewId"), CONSTRAINT "CHK_55e3f752b77d6db7979d831c37" CHECK ("rating" >= 1 AND "rating" <= 5), CONSTRAINT "PK_8389f9e087a57689cd5be8b2b13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cancel-interview_cancelby_enum" AS ENUM('Applicant', 'Company')`);
        await queryRunner.query(`CREATE TABLE "cancel-interview" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reason" character varying, "cancelBy" "public"."cancel-interview_cancelby_enum" NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "interviewId" uuid, CONSTRAINT "REL_0888955f5632638166d1edad51" UNIQUE ("interviewId"), CONSTRAINT "PK_d876e20fe7347355457f08f2839" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."interviews_type_enum" AS ENUM('Technical', 'HR', 'Final')`);
        await queryRunner.query(`CREATE TYPE "public"."interviews_status_enum" AS ENUM('Scheduled', 'Completed', 'Cancelled', 'Rescheduled')`);
        await queryRunner.query(`CREATE TABLE "interviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."interviews_type_enum" NOT NULL DEFAULT 'Technical', "status" "public"."interviews_status_enum" NOT NULL DEFAULT 'Scheduled', "scheduledAt" TIMESTAMP WITH TIME ZONE NOT NULL, "meetingLink" character varying NOT NULL, "durationMin" integer NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "applicationId" uuid, CONSTRAINT "PK_fd41af1f96d698fa33c2f070f47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reject-cv" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reason" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "applicationId" uuid, CONSTRAINT "REL_1e2c1e8293dcdaca3719dbb94a" UNIQUE ("applicationId"), CONSTRAINT "PK_445fa50d3594efddb8f8ee47d36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."job_applicant_status_enum" AS ENUM('New', 'Screening', 'interview', 'Offered', 'Hired', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."job_applicant_statusai_enum" AS ENUM('pending', 'active', 'completed', 'failed', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "job_applicant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."job_applicant_status_enum" NOT NULL DEFAULT 'New', "about" character varying NOT NULL, "statusAi" "public"."job_applicant_statusai_enum" NOT NULL DEFAULT 'pending', "result" json, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "hiredAt" TIMESTAMP WITH TIME ZONE, "screenAt" TIMESTAMP WITH TIME ZONE, "sendOfferAt" TIMESTAMP WITH TIME ZONE, "interviewAt" TIMESTAMP WITH TIME ZONE, "rejectAt" TIMESTAMP WITH TIME ZONE, "jobId" uuid, "applicantId" uuid, "cvId" uuid, CONSTRAINT "UQ_c2160c2da37f8325cd9c1b2b448" UNIQUE ("jobId", "applicantId"), CONSTRAINT "PK_66f870f5e5792506f5901a02e45" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."CV_status_enum" AS ENUM('pending', 'active', 'completed', 'failed', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "CV" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "url" character varying NOT NULL, "status" "public"."CV_status_enum" NOT NULL DEFAULT 'pending', "asset_id" character varying, "isPrimary" boolean NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "applicantId" uuid, CONSTRAINT "PK_a7e0c0895ceb856a1420ce991fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "applicantId" uuid, CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experience" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "company" character varying NOT NULL, "startDate" TIMESTAMP WITH TIME ZONE NOT NULL, "endDate" TIMESTAMP WITH TIME ZONE NOT NULL, "description" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "applicantId" uuid, CONSTRAINT "PK_5e8d5a534100e1b17ee2efa429a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."industry_name_enum" AS ENUM('Software Development', 'Artificial Intelligence & Machine Learning', 'Data Science & Big Data', 'Cybersecurity', 'Cloud Computing', 'Networking & Infrastructure', 'Embedded Systems & IoT', 'Game Development', 'UI/UX Design', 'Blockchain & FinTech', 'AR / VR (Augmented & Virtual Reality)', 'Hardware & Electronics')`);
        await queryRunner.query(`CREATE TABLE "industry" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."industry_name_enum" NOT NULL, "projectId" integer NOT NULL DEFAULT '20261', CONSTRAINT "UQ_e756cbed5e9f27221c238f11fcc" UNIQUE ("name"), CONSTRAINT "PK_fc3e38485cff79e9fbba8f13831" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applicant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying, "job_title" character varying, "candidateId" character varying, "userId" uuid, "industryId" uuid, CONSTRAINT "REL_546a819aa07c196d7aa0f9d17d" UNIQUE ("userId"), CONSTRAINT "PK_f4a6e907b8b17f293eb073fc5ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('Applicant', 'Company')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "location" character varying, "linkedIn_profile" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'Applicant', "refreshToken" character varying, "isEmailVerified" boolean NOT NULL DEFAULT false, "isDelete" boolean NOT NULL DEFAULT false, "createAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."outbox_event_type_enum" AS ENUM('SEND_VERIFICATION_EMAIL', 'SEND_RESET_PASSWORD', 'SEND_RESTORE_EMAIL')`);
        await queryRunner.query(`CREATE TYPE "public"."outbox_status_enum" AS ENUM('PENDING', 'SENT', 'FAILED', 'PROCESSING')`);
        await queryRunner.query(`CREATE TABLE "outbox" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_type" "public"."outbox_event_type_enum" NOT NULL, "payload" jsonb NOT NULL, "status" "public"."outbox_status_enum" NOT NULL DEFAULT 'PENDING', "retryCount" integer NOT NULL DEFAULT '0', "nextRetryAt" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_340ab539f309f03bdaa14aa7649" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user-token" ADD CONSTRAINT "FK_6c43c95ddb18b3ae863e7c9d06e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "specialization" ADD CONSTRAINT "FK_353f54a6f585a07c0f90140797c" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_c41a1d36702f2cd0403ce58d33a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recommendation-batch" ADD CONSTRAINT "FK_98f749fff6640d49e6779d6d1dc" FOREIGN KEY ("cvId") REFERENCES "CV"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recommend-jobs" ADD CONSTRAINT "FK_406b6232d41c2503df1de5f2575" FOREIGN KEY ("batchId") REFERENCES "recommendation-batch"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recommend-jobs" ADD CONSTRAINT "FK_c48271cec9bbe39143ad927fce8" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_6ce4483dc65ed9d2e171269d801" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" ADD CONSTRAINT "FK_6810b7bcf49a32fad3dacab7729" FOREIGN KEY ("applicationId") REFERENCES "job_applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobOffer" ADD CONSTRAINT "FK_3ef8642da65cce502da75501219" FOREIGN KEY ("applicationId") REFERENCES "job_applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedback" ADD CONSTRAINT "FK_1da270251d13dd20cf2a50271f1" FOREIGN KEY ("interviewId") REFERENCES "interviews"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cancel-interview" ADD CONSTRAINT "FK_0888955f5632638166d1edad512" FOREIGN KEY ("interviewId") REFERENCES "interviews"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interviews" ADD CONSTRAINT "FK_ba82c76bf124871821aedc35b7a" FOREIGN KEY ("applicationId") REFERENCES "job_applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reject-cv" ADD CONSTRAINT "FK_1e2c1e8293dcdaca3719dbb94a2" FOREIGN KEY ("applicationId") REFERENCES "job_applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_f4887ecc2367922eb6feac0f1cd" FOREIGN KEY ("jobId") REFERENCES "jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_c78f9fee4defea0110ba5ef0ed0" FOREIGN KEY ("applicantId") REFERENCES "applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applicant" ADD CONSTRAINT "FK_f04802c55e270cf2b9f70d6e42d" FOREIGN KEY ("cvId") REFERENCES "CV"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CV" ADD CONSTRAINT "FK_0a4835f22b6d5b52b1ba4ba59d2" FOREIGN KEY ("applicantId") REFERENCES "applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_09ed4d6c331fbfb5a455d868db7" FOREIGN KEY ("applicantId") REFERENCES "applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_9c837a4822a45cf6bc4938a1bba" FOREIGN KEY ("applicantId") REFERENCES "applicant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "FK_546a819aa07c196d7aa0f9d17db" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "FK_00099a40978bff6411793df6bd0" FOREIGN KEY ("industryId") REFERENCES "industry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "FK_00099a40978bff6411793df6bd0"`);
        await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "FK_546a819aa07c196d7aa0f9d17db"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_9c837a4822a45cf6bc4938a1bba"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_09ed4d6c331fbfb5a455d868db7"`);
        await queryRunner.query(`ALTER TABLE "CV" DROP CONSTRAINT "FK_0a4835f22b6d5b52b1ba4ba59d2"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_f04802c55e270cf2b9f70d6e42d"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_c78f9fee4defea0110ba5ef0ed0"`);
        await queryRunner.query(`ALTER TABLE "job_applicant" DROP CONSTRAINT "FK_f4887ecc2367922eb6feac0f1cd"`);
        await queryRunner.query(`ALTER TABLE "reject-cv" DROP CONSTRAINT "FK_1e2c1e8293dcdaca3719dbb94a2"`);
        await queryRunner.query(`ALTER TABLE "interviews" DROP CONSTRAINT "FK_ba82c76bf124871821aedc35b7a"`);
        await queryRunner.query(`ALTER TABLE "cancel-interview" DROP CONSTRAINT "FK_0888955f5632638166d1edad512"`);
        await queryRunner.query(`ALTER TABLE "feedback" DROP CONSTRAINT "FK_1da270251d13dd20cf2a50271f1"`);
        await queryRunner.query(`ALTER TABLE "jobOffer" DROP CONSTRAINT "FK_3ef8642da65cce502da75501219"`);
        await queryRunner.query(`ALTER TABLE "hiredDetails" DROP CONSTRAINT "FK_6810b7bcf49a32fad3dacab7729"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_6ce4483dc65ed9d2e171269d801"`);
        await queryRunner.query(`ALTER TABLE "recommend-jobs" DROP CONSTRAINT "FK_c48271cec9bbe39143ad927fce8"`);
        await queryRunner.query(`ALTER TABLE "recommend-jobs" DROP CONSTRAINT "FK_406b6232d41c2503df1de5f2575"`);
        await queryRunner.query(`ALTER TABLE "recommendation-batch" DROP CONSTRAINT "FK_98f749fff6640d49e6779d6d1dc"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_c41a1d36702f2cd0403ce58d33a"`);
        await queryRunner.query(`ALTER TABLE "specialization" DROP CONSTRAINT "FK_353f54a6f585a07c0f90140797c"`);
        await queryRunner.query(`ALTER TABLE "user-token" DROP CONSTRAINT "FK_6c43c95ddb18b3ae863e7c9d06e"`);
        await queryRunner.query(`DROP TABLE "outbox"`);
        await queryRunner.query(`DROP TYPE "public"."outbox_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."outbox_event_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "applicant"`);
        await queryRunner.query(`DROP TABLE "industry"`);
        await queryRunner.query(`DROP TYPE "public"."industry_name_enum"`);
        await queryRunner.query(`DROP TABLE "experience"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP TABLE "CV"`);
        await queryRunner.query(`DROP TYPE "public"."CV_status_enum"`);
        await queryRunner.query(`DROP TABLE "job_applicant"`);
        await queryRunner.query(`DROP TYPE "public"."job_applicant_statusai_enum"`);
        await queryRunner.query(`DROP TYPE "public"."job_applicant_status_enum"`);
        await queryRunner.query(`DROP TABLE "reject-cv"`);
        await queryRunner.query(`DROP TABLE "interviews"`);
        await queryRunner.query(`DROP TYPE "public"."interviews_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."interviews_type_enum"`);
        await queryRunner.query(`DROP TABLE "cancel-interview"`);
        await queryRunner.query(`DROP TYPE "public"."cancel-interview_cancelby_enum"`);
        await queryRunner.query(`DROP TABLE "feedback"`);
        await queryRunner.query(`DROP TYPE "public"."feedback_nextstep_enum"`);
        await queryRunner.query(`DROP TABLE "jobOffer"`);
        await queryRunner.query(`DROP TYPE "public"."jobOffer_status_enum"`);
        await queryRunner.query(`DROP TABLE "hiredDetails"`);
        await queryRunner.query(`DROP TABLE "jobs"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_statusai_enum"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_seniority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_workmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."jobs_type_enum"`);
        await queryRunner.query(`DROP TABLE "recommend-jobs"`);
        await queryRunner.query(`DROP TABLE "recommendation-batch"`);
        await queryRunner.query(`DROP TYPE "public"."recommendation-batch_status_enum"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP TABLE "specialization"`);
        await queryRunner.query(`DROP TABLE "user-token"`);
        await queryRunner.query(`DROP TYPE "public"."user-token_type_enum"`);
    }

}
